import type { GeoSite } from "@/lib/types";

export const SITES: GeoSite[] = [
  {
    id: "patmos",
    name: "Patmos",
    lat: 37.325,
    lng: 26.548,
    summary: "The island where John received the Revelation while in exile.",
    expeditionId: "interpreters-chamber",
    searchTerms: ["Patmos", "Cave of the Apocalypse"],
  },
  {
    id: "ephesus",
    name: "Ephesus",
    lat: 37.9397,
    lng: 27.3408,
    summary: "Harbour city of the first church letter: love left, lampstand at risk.",
    expeditionId: "seven-cities",
    searchTerms: ["Ephesus ruins", "Library of Celsus"],
  },
  {
    id: "smyrna",
    name: "Smyrna",
    lat: 38.4192,
    lng: 27.1287,
    summary: "A suffering church promised the crown of life.",
    expeditionId: "seven-cities",
    searchTerms: ["Smyrna agora Izmir"],
  },
  {
    id: "pergamum",
    name: "Pergamum",
    lat: 39.1208,
    lng: 27.1836,
    summary: "City of the throne-like acropolis and the 'where Satan dwells' letter.",
    expeditionId: "seven-cities",
    searchTerms: ["Pergamon acropolis altar"],
  },
  {
    id: "thyatira",
    name: "Thyatira",
    lat: 38.9215,
    lng: 27.8363,
    summary: "Trade-guild city addressed for endurance mixed with corruption.",
    expeditionId: "seven-cities",
    searchTerms: ["Thyatira Akhisar"],
  },
  {
    id: "sardis",
    name: "Sardis",
    lat: 38.4883,
    lng: 28.0403,
    summary: "Once-great capital warned that it had a name of life but was dead.",
    expeditionId: "seven-cities",
    searchTerms: ["Sardis synagogue temple Artemis"],
  },
  {
    id: "philadelphia",
    name: "Philadelphia",
    lat: 38.3506,
    lng: 28.5172,
    summary: "The open-door church of brotherly loyalty.",
    expeditionId: "seven-cities",
    searchTerms: ["Alaşehir Philadelphia church"],
  },
  {
    id: "laodicea",
    name: "Laodicea",
    lat: 37.836,
    lng: 29.1075,
    summary: "Wealthy water-city of the lukewarm warning and the knocking Christ.",
    expeditionId: "seven-cities",
    searchTerms: ["Laodicea on the Lycus"],
  },
  {
    id: "jerusalem",
    name: "Jerusalem",
    lat: 31.778,
    lng: 35.235,
    summary: "Sanctuary, judgment, and the city the New Jerusalem both remembers and heals.",
    expeditionId: "sanctuary-vault",
    searchTerms: ["Jerusalem temple mount archaeology"],
  },
  {
    id: "rome",
    name: "Rome",
    lat: 41.9028,
    lng: 12.4964,
    summary: "Imperial and later religious centre in historicist readings of the beasts.",
    expeditionId: "sea-beast",
    searchTerms: ["Roman forum archaeology"],
  },
  {
    id: "constantinople",
    name: "Constantinople",
    lat: 41.0082,
    lng: 28.9784,
    summary: "Eastern capital on the trumpet trail and later Ottoman dossiers.",
    expeditionId: "trumpet-trail",
    searchTerms: ["Hagia Sophia Constantinople"],
  },
  {
    id: "babylon",
    name: "Babylon",
    lat: 32.542,
    lng: 44.421,
    summary: "The name Revelation reuses as a symbol of a world-system opposed to God.",
    expeditionId: "mystery-babylon",
    searchTerms: ["Babylon Ishtar gate ruins"],
  },
  {
    id: "sinai",
    name: "Sinai",
    lat: 28.539,
    lng: 33.975,
    summary: "Law, covenant, and the Sabbath seal's creation memory.",
    expeditionId: "sabbath-seal",
    searchTerms: ["Mount Sinai monastery"],
  },
];
