import type { SymbolEntry } from "@/lib/types";

export const SYMBOLS: SymbolEntry[] = [
  {
    id: "lampstand",
    name: "Lampstands",
    glyph: "🕎",
    definition: "Seven golden lampstands stand in the first vision. The book names them before we invent a meaning.",
    primaryPassages: ["Rev 1:12-13", "Rev 1:20"],
    historicist:
      "Revelation 1:20: the seven lampstands are the seven churches. First lesson: when Scripture explains its own image, keep that explanation.",
    related: ["lamb"],
    unlockAfter: ["interpreters-chamber"],
  },
  {
    id: "woman",
    name: "Woman",
    glyph: "☉",
    definition: "In apocalyptic imagery a woman often stands for a community of worshippers.",
    primaryPassages: ["Rev 12:1", "Rev 17:3-5", "Jer 6:2", "2 Cor 11:2"],
    historicist:
      "Revelation 12's woman is the faithful people of God; Revelation 17's woman is an unfaithful religious-political system. Same symbol-family, opposite allegiance.",
    related: ["dragon", "child", "babylon", "wilderness"],
    unlockAfter: ["woman-dragon"],
  },
  {
    id: "dragon",
    name: "Dragon",
    glyph: "✶",
    definition: "A devouring antagonist behind earthly powers.",
    primaryPassages: ["Rev 12:3-9", "Rev 20:2", "Isa 27:1"],
    historicist:
      "Revelation 12:9 names the dragon: the devil, Satan, the ancient serpent. Earthly beasts act as his instruments, not his replacement.",
    related: ["woman", "sea-beast", "war"],
    unlockAfter: ["woman-dragon"],
  },
  {
    id: "child",
    name: "Male child",
    glyph: "✦",
    definition: "The promised offspring who will rule the nations.",
    primaryPassages: ["Rev 12:5", "Ps 2:7-9", "Rev 19:15"],
    historicist:
      "Caught up to God and to his throne: Christ, not a merely political messiah. The war is older than any modern headline.",
    related: ["woman", "dragon", "throne"],
    unlockAfter: ["woman-dragon"],
  },
  {
    id: "beast-sea",
    name: "Beast from the sea",
    glyph: "≋",
    definition: "A composite political-religious power rising from peoples.",
    primaryPassages: ["Rev 13:1-10", "Dan 7:2-8", "Rev 17:15"],
    historicist:
      "Waters are peoples (Rev 17:15). The composite of lion, bear, leopard and the fourth beast of Daniel 7 points to a successor of pagan Rome that speaks blasphemy, persecutes, and rules 42 months / 1260 days.",
    related: ["dragon", "wound", "earth-beast", "mark"],
    unlockAfter: ["sea-beast"],
  },
  {
    id: "beast-earth",
    name: "Beast from the earth",
    glyph: "▲",
    definition: "A second power, lamb-like in appearance, dragon-like in speech.",
    primaryPassages: ["Rev 13:11-18", "Rev 19:20"],
    historicist:
      "Earth (as opposed to sea) suggests a newer, less crowded stage of history. Lamb-like horns recall Christ and liberty; dragon-speech is coerced worship. Classic SDA reading: the United States in its end-time role.",
    related: ["beast-sea", "image", "mark"],
    unlockAfter: ["earth-beast"],
  },
  {
    id: "mark",
    name: "Mark of the beast",
    glyph: "▣",
    definition: "A sign of allegiance in thought (forehead) and action (hand).",
    primaryPassages: ["Rev 13:16-17", "Rev 14:9-12", "Deut 6:6-8"],
    historicist:
      "Not first a gadget. In Deuteronomy, hand and forehead are loyalty to God's law. The SDA reading places the crisis in worship: God's Sabbath seal versus an enforced counterfeit rest/worship day. Individuals are not the beast.",
    related: ["seal", "sabbath", "worship", "666"],
    unlockAfter: ["the-mark"],
  },
  {
    id: "666",
    name: "Six hundred sixty-six",
    glyph: "χξϛ",
    definition: "A human number requiring wisdom, not panic.",
    primaryPassages: ["Rev 13:18"],
    historicist:
      "It is the number of a man / humanity, bound to the beast's identity. Historicist writers have used gematria (including debated Latin titles). Hold the method loosely; hold the allegiance question firmly.",
    related: ["mark", "beast-sea"],
    unlockAfter: ["the-mark"],
  },
  {
    id: "babylon",
    name: "Babylon",
    glyph: "⚭",
    definition: "A city-name reused as a world-system of confusion and coercion.",
    primaryPassages: ["Rev 14:8", "Rev 17", "Rev 18", "Gen 11:1-9"],
    historicist:
      "Not merely ancient Iraq. A religious-political economy opposed to the Lamb, historically associated with apostate Christianity and, in the end, a broader coalition. The call is 'come out,' not 'despise people.'",
    related: ["woman", "wine", "merchants"],
    unlockAfter: ["mystery-babylon"],
  },
  {
    id: "lamb",
    name: "Lamb",
    glyph: "♰",
    definition: "The slain-and-standing centre of Revelation's throne room.",
    primaryPassages: ["Rev 5:6", "John 1:29", "Rev 14:1"],
    historicist:
      "Jesus Christ crucified and risen. Every beast, trumpet and plague is interpreted from this centre, not from fear.",
    related: ["scroll", "worship", "blood"],
    unlockAfter: ["throne-room"],
  },
  {
    id: "scroll",
    name: "Sealed scroll",
    glyph: "☰",
    definition: "The title-deed of history that only the Lamb can open.",
    primaryPassages: ["Rev 5:1-10", "Rev 6"],
    historicist:
      "The seals disclose the conflict of the church in history. Recapitulation, not a single linear horror film.",
    related: ["lamb", "seals"],
    unlockAfter: ["throne-room"],
  },
  {
    id: "seal",
    name: "Seal of God",
    glyph: "◉",
    definition: "A mark of belonging placed on the forehead of the servants of God.",
    primaryPassages: ["Rev 7:2-3", "Rev 14:1", "Ezek 9:4", "Exod 31:13"],
    historicist:
      "The opposite of the mark. SDA reading links the end-time seal to loyal worship of the Creator, expressed in the Sabbath commandment as a sign of God's authority.",
    related: ["sabbath", "mark", "worship"],
    unlockAfter: ["sabbath-seal"],
  },
  {
    id: "sabbath",
    name: "Sabbath",
    glyph: "◐",
    definition: "Seventh-day rest rooted in Creation and covenant.",
    primaryPassages: ["Gen 2:1-3", "Exod 20:8-11", "Rev 14:6-7"],
    historicist:
      "The first angel calls the world to worship the Creator. The Sabbath is treated as a living memorial of that claim, not a footnote for specialists.",
    related: ["seal", "worship", "creation"],
    unlockAfter: ["sabbath-seal"],
  },
  {
    id: "horns",
    name: "Horns",
    glyph: "∧",
    definition: "Strength, kings, or divisions of power.",
    primaryPassages: ["Dan 7:24", "Rev 13:1", "Rev 17:12"],
    historicist: "Ten horns in Daniel/Revelation are successive or concurrent kingdoms, not merely a future ten-man cabinet.",
    related: ["beast-sea", "babylon"],
    unlockAfter: ["sea-beast"],
  },
  {
    id: "sea",
    name: "Sea / waters",
    glyph: "≈",
    definition: "Peoples, crowds, and restless nations when used symbolically.",
    primaryPassages: ["Rev 17:15", "Isa 17:12", "Dan 7:2-3"],
    historicist: "A beast from the sea rises among populated empires. A beast from the earth rises elsewhere.",
    related: ["beast-sea", "earth-beast"],
    unlockAfter: ["sea-beast"],
  },
  {
    id: "wine",
    name: "Wine of Babylon",
    glyph: "☕",
    definition: "Intoxicating teaching that confuses judgment and loyalty.",
    primaryPassages: ["Rev 14:8", "Rev 17:2", "Jer 51:7"],
    historicist: "False worship and coercive religion, not a temperance pamphlet only.",
    related: ["babylon", "worship"],
    unlockAfter: ["three-messengers"],
  },
  {
    id: "sanctuary",
    name: "Sanctuary",
    glyph: "⌂",
    definition: "God's dwelling pattern: courtyard, holy place, most holy place.",
    primaryPassages: ["Exod 25:8-9", "Heb 8:1-5", "Dan 8:14"],
    historicist:
      "Earthly ritual explains a heavenly ministry. 1844 is read as the antitypical Day of Atonement beginning, not as the Second Coming.",
    related: ["judgment", "lamb", "law"],
    unlockAfter: ["sanctuary-vault"],
  },
  {
    id: "judgment",
    name: "Judgment",
    glyph: "⚖",
    definition: "God's public setting-right of the universe.",
    primaryPassages: ["Rev 14:7", "Dan 7:9-14", "Rev 20:11-15"],
    historicist:
      "Investigative (pre-advent) and executive (final) phases. The books are evidence, not a threat to the Lamb's people.",
    related: ["sanctuary", "book-of-life"],
    unlockAfter: ["2300-day-code"],
  },
  {
    id: "book-of-life",
    name: "Book of Life",
    glyph: "▤",
    definition: "The register of those who belong to the Lamb.",
    primaryPassages: ["Rev 20:12-15", "Rev 21:27", "Phil 4:3"],
    historicist: "Final judgment is evidence-based. Names, not rumours.",
    related: ["judgment"],
    unlockAfter: ["final-case"],
  },
  {
    id: "new-jerusalem",
    name: "New Jerusalem",
    glyph: "✧",
    definition: "The city that comes down: God dwelling with humanity.",
    primaryPassages: ["Rev 21:1-4", "Rev 22:1-5", "Isa 65:17-19"],
    historicist: "The expedition's destination. Restoration, not endless excavation of beasts.",
    related: ["tree", "river"],
    unlockAfter: ["lost-city"],
  },
];
