import type { TimelineEvent } from "@/lib/types";

export const TIMELINE: TimelineEvent[] = [
  {
    id: "creation",
    label: "Creation Sabbath",
    year: "Beginning",
    kind: "biblical",
    body: "Rest is written into the world's first week. Worship later argues about who made the world.",
    expeditionId: "sabbath-seal",
  },
  {
    id: "decree-457",
    label: "Artaxerxes' decree",
    year: "457 BC",
    kind: "historical",
    body: "The decree to restore and build Jerusalem is the historicist starting gun for the 70 weeks and the 2300 days.",
    expeditionId: "2300-day-code",
  },
  {
    id: "baptism",
    label: "Messiah anointed",
    year: "AD 27",
    kind: "biblical",
    body: "69 weeks (483 years) from 457 BC reach the baptism of Jesus — the historicist reading of Daniel 9:25.",
    expeditionId: "2300-day-code",
  },
  {
    id: "cross",
    label: "Mid-week cross",
    year: "AD 31",
    kind: "biblical",
    body: "In the midst of the seventieth week the Messiah is cut off. Sacrifice and offering cease in their old meaning.",
    expeditionId: "2300-day-code",
  },
  {
    id: "stephen",
    label: "Gospel to the nations",
    year: "AD 34",
    kind: "biblical",
    body: "The 70 weeks close as the church is scattered and the mission becomes unmistakably worldwide.",
    expeditionId: "2300-day-code",
  },
  {
    id: "patmos",
    label: "John on Patmos",
    year: "c. AD 95",
    kind: "biblical",
    body: "Revelation is given to a prisoner, not a court prophet. The setting is persecution and worship.",
    expeditionId: "interpreters-chamber",
  },
  {
    id: "constantine",
    label: "Imperial favour",
    year: "AD 313–337",
    kind: "historical",
    body: "The church moves from hunted to hosted. Pergamum's compromise becomes historically imaginable.",
    expeditionId: "seven-cities",
  },
  {
    id: "538",
    label: "1260 years begin",
    year: "AD 538",
    kind: "prophetic",
    body: "Classic historicist dating for the 42 months / 1260 days / time, times and half a time of papal supremacy.",
    expeditionId: "sea-beast",
  },
  {
    id: "reformation",
    label: "Reformation fracture",
    year: "1517+",
    kind: "historical",
    body: "Sardis: a name of life. Scripture returns to the people. The work is unfinished.",
    expeditionId: "seven-cities",
  },
  {
    id: "1798",
    label: "Deadly wound",
    year: "1798",
    kind: "prophetic",
    body: "The captivity of the pope by Berthier's army is read as a deadly wound to the sea beast's supremacy.",
    expeditionId: "sea-beast",
  },
  {
    id: "1844",
    label: "2300 evenings-mornings",
    year: "1844",
    kind: "doctrinal",
    body: "457 BC + 2300 years. SDA reading: the heavenly sanctuary's Day of Atonement phase begins — investigative judgment, not the Advent itself.",
    expeditionId: "2300-day-code",
  },
  {
    id: "advent-awakening",
    label: "Advent awakening",
    year: "1798–1844",
    kind: "historical",
    body: "Philadelphia's open door: Bible societies, prophecy study, and a worldwide expectation of the Advent.",
    expeditionId: "three-messengers",
  },
  {
    id: "second-coming",
    label: "Return of the King",
    year: "Future",
    kind: "biblical",
    body: "Visible, personal, glorious. The Lamb is also the Rider. No secret epilogue.",
    expeditionId: "return-of-the-king",
  },
  {
    id: "millennium",
    label: "Thousand years",
    year: "After the Advent",
    kind: "doctrinal",
    body: "Saints with Christ; earth desolate; Satan bound by the absence of people to deceive until the second resurrection.",
    expeditionId: "thousand-years",
  },
  {
    id: "new-earth",
    label: "God dwelling with us",
    year: "Forever",
    kind: "biblical",
    body: "The investigation ends in a city that does not need a temple, because the Lord God and the Lamb are its temple.",
    expeditionId: "the-beginning",
  },
];
